baseURL = 'https://damondb.github.io/2026/'
languageCode = 'en-us'
title = 'DAMON 2026 workshop'

disableKinds = ["taxonomy", ]

[params]
# Optional change logo file
  [params.logo]
    small = "logo/DaMon_logo.png"
#    large = "logo/DaMon_logo_20yrs.png"
  [params.banner]
    image = "img/title_Bengaluru.jpg"
    [[params.banner.sponsors]]
    name = "SAP"
    file = "img/sap_logo.png"
    style = "max-width: 200px"
  [params.workshop]
    number = "22"
    title = "Data Management on New Hardware (DaMoN)"
    date = "Monday June 1st, 2026"
  [params.conference]
    title = "ACM SIGMOD/PODS"
    link = "https://2026.sigmod.org/"
    year = 2026
    location = "Bengaluru, India" 

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true # default is false
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        enableDefault = true
        errorLevel = 'warning' # ignore (default), warning, or error (fails the build)

[module]
  [[module.imports]]
    path = "github.com/damondb/hugo-damon-db"

[build]
  writeStats = true
